- name: Install pip and docker module
  hosts: all
  become: yes
  pre_tasks:
    - name: update cache
      apt:
        update_cache: true
  roles:
    - role: geerlingguy.pip
  tasks:
    - name: Create env for redmine
      template:
        src: ./playbooks/templates/env.j2
        dest: '.env'
      tags: env

    - name: Start container
      community.docker.docker_container:
        name: task-manager-redmine
        image: redmine:5.1.2-alpine3.18
        cleanup: true
        detach: true
        output_logs: true
        ports:
          - 80:3000
          - 443:3000
        restart: true
        restart_policy: "always"
        env_file: '.env'
